// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ0LnEoG9zZI3yMeSyqKMdVjny0mRQU3o',
    appId: '1:645394195211:web:d7e6efba39ea4452fa780e',
    messagingSenderId: '645394195211',
    projectId: 'flutter-prep-e8c50',
    authDomain: 'flutter-prep-e8c50.firebaseapp.com',
    databaseURL: 'https://flutter-prep-e8c50-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-e8c50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUK4yIHDBqWHzUDs7FQailJveZa7KUnAk',
    appId: '1:645394195211:android:9437b6126dee3b46fa780e',
    messagingSenderId: '645394195211',
    projectId: 'flutter-prep-e8c50',
    databaseURL: 'https://flutter-prep-e8c50-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-e8c50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3sCO2Jmyapifnd-WF2I_Ex7Gog9RSAoA',
    appId: '1:645394195211:ios:4161ed58192a6fd2fa780e',
    messagingSenderId: '645394195211',
    projectId: 'flutter-prep-e8c50',
    databaseURL: 'https://flutter-prep-e8c50-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-e8c50.appspot.com',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3sCO2Jmyapifnd-WF2I_Ex7Gog9RSAoA',
    appId: '1:645394195211:ios:91df0a6042331408fa780e',
    messagingSenderId: '645394195211',
    projectId: 'flutter-prep-e8c50',
    databaseURL: 'https://flutter-prep-e8c50-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-e8c50.appspot.com',
    iosBundleId: 'com.example.shoppingList.RunnerTests',
  );
}
